config/routes.rb
Rails.application.routes.draw do

  root to: 'rates#index'

  get '/convert' => 'rates#convert'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]

  # GET /rates or /rates.json
  def index
    @countries = ["USD", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "FOK", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KID", "KMF", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STN", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TVD", "TWD", "TZS", "UAH", "UGX", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XCD", "XDR", "XOF", "XPF", "YER", "ZAR", "ZMW"]
  end


  def convert
    api = ENV["FOREX_API_KEY"]
    rate1 = params[:rate1]
    rate2 = params[:rate2]
    amount = params[:amount]
    response = HTTParty.get("https://v6.exchangerate-api.com/v6/#{api}/pair/#{rate1}/#{rate2}/#{amount}")
    @results = response
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forex_api_helper.rb
module ForexApiHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForexApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rates/convert.html.erb
<h3>
  Result: <%= number_to_currency(@results["conversion_result"]) %> 
</h3>

<h2>
  Convert again: <%= link_to("Convert", root_path ) %>
</h2>

app/views/rates/index.html.erb
<%= form_with(url: convert_path, method: 'get',) do %>
    <div class="field1">
        <h2>Rate 1</h2>
        <%= select_tag "rate1", options_for_select(@countries, params["rate1"]) %>
    </div>

    <div class="field2">
        <h2>Rate 2</h2>
        <%= select_tag "rate2", options_for_select(@countries, params["rate2"]) %>
    </div>

    <div class="field3">
        <h2>Amount</h2>
        <%= number_field_tag :amount %>
    </div>

    <div class="actions">
        <%= submit_tag "convert" %>

    </div>
<% end %>